export const GET_BY_EMPLOYEE_ID_REQUEST =
  "GET_BY_EMPLOYEE_ID_CERTIFICATE_REQUEST";
export const GET_BY_EMPLOYEE_ID_SUCCESS =
  "GET_BY_EMPLOYEE_ID_CERTIFICATE_SUCCESS";
export const GET_BY_EMPLOYEE_ID_ERROR = "GET_BY_EMPLOYEE_ID_CERTIFICATE_ERROR";
export const CREATE_REQUEST = "CREATE_CERTIFICATE_REQUEST";
export const CREATE_SUCCESS = "CREATE_CERTIFICATE_SUCCESS";
export const CREATE_ERROR = "CREATE_CERTIFICATE_ERROR";
export const DELETE_REQUEST = "DELETE_CERTIFICATE_REQUEST";
export const DELETE_SUCCESS = "DELETE_CERTIFICATE_SUCCESS";
export const DELETE_ERROR = "DELETE_CERTIFICATE_ERROR";
export const UPDATE_REQUEST = "UPDATE_CERTIFICATE_REQUEST";
export const UPDATE_SUCCESS = "UPDATE_CERTIFICATE_SUCCESS";
export const UPDATE_ERROR = "UPDATE_CERTIFICATE_ERROR";
